# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import sigpaeHistoricos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('DCM', 'Departamento de Ciencia de los Materiales'), ('DCT', 'Departamento de Ciencias de la Tierra'), ('DCTI', 'Departamento de Computación y Tecnología de Información'), ('DCCE', 'Departamento de Cómputo Científico y Estadística'), ('DCTE', 'Departamento de Conversión y Transporte de Energía'), ('DEC', 'Departamento de Electrónica y Circuitos'), ('DF', 'Departamento de Física'), ('DMPA', 'Departamento de Matemáticas Puras y Aplicadas'), ('DM', 'Departamento de Mecánica'), ('DPS', 'Departamento de Procesos y Sistemas'), ('DQ', 'Departamento de Química'), ('DTFT', 'Departamento de Termodinámica y Fenómenos de Transferencia')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/%Y/%m/%d', validators=[sigpaeHistoricos.models.valid_extension])),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.CharField(choices=[('sep-dic', 'Septiembre-Diciembre'), ('ene-mar', 'Enero-Marzo'), ('abr-jul', 'Abril-Julio'), ('intensivo', 'Intensivo')], max_length=9)),
            ],
        ),
    ]
