# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sigpaeHistoricos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/', validators=[sigpaeHistoricos.models.valid_extension])),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('texto', models.TextField(null=True, verbose_name='Texto')),
                ('denominacion', models.TextField(null=True, verbose_name='Denominación')),
                ('periodo', models.CharField(choices=[('sep-dic', 'sep-dic'), ('ene-mar', 'ene-mar'), ('abr-jul', 'abr-jul'), ('intensivo', 'intensivo')], max_length=9, null=True, verbose_name='Período')),
                ('año', models.PositiveIntegerField(choices=[(1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], null=True, verbose_name='Año')),
                ('horas_semanales', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Horas Semanales')),
                ('creditos', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)], verbose_name='Créditos')),
                ('requisitos', models.TextField(null=True, verbose_name='Requisitos')),
                ('objetivos', models.TextField(null=True, verbose_name='Objetivos')),
                ('sinopticos', models.TextField(null=True, verbose_name='Contenidos Sinópticos')),
                ('estrategias_metodologicas', models.TextField(null=True, verbose_name='Estrategias Metodológicas')),
                ('estrategias_evaluacion', models.TextField(null=True, verbose_name='Estrategias de Evaluación')),
                ('ftes_info_recomendadas', models.TextField(null=True, verbose_name='Fuentes de Información Recomendadas')),
                ('observaciones', models.TextField(null=True, verbose_name='Observaciones')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sigpaeHistoricos.Departamento', verbose_name='Departamento')),
            ],
        ),
    ]
