# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigpaeHistoricos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Decanato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='horas_semanales',
        ),
        migrations.RemoveField(
            model_name='pdfs',
            name='titulo',
        ),
        migrations.AddField(
            model_name='pdfs',
            name='codigo',
            field=models.CharField(max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='encargado',
            field=models.CharField(max_length=100, null=True, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='horas_laboratorio',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Horas de laboratorio'),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='horas_practica',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Horas de práctica'),
        ),
        migrations.AddField(
            model_name='pdfs',
            name='horas_teoria',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Horas de teoría'),
        ),
        migrations.AddField(
            model_name='coordinacion',
            name='decanato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sigpaeHistoricos.Decanato', verbose_name='Decanato'),
        ),
    ]
