# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import programa.models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/%Y/%m/%d', validators=[programa.models.valid_extension])),
                ('text', models.TextField()),
            ],
        ),
    ]
