# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='departments',
            field=models.CharField(choices=[(b'DCM', b'Departamento de Ciencia de los Materiales'), (b'DCT', b'Departamento de Ciencias de la Tierra'), (b'DCTI', b'Departamento de Computaci\xc3\xb3n y Tecnolog\xc3\xada de Informaci\xc3\xb3n'), (b'DCCE', b'Departamento de C\xc3\xb3mputo Cient\xc3\xadfico y Estad\xc3\xadstica'), (b'DCTE', b'Departamento de Conversi\xc3\xb3n y Transporte de Energ\xc3\xada'), (b'DEC', b'Departamento de Electr\xc3\xb3nica y Circuitos'), (b'DF', b'Departamento de F\xc3\xadsica'), (b'DMPA', b'Departamento de Matem\xc3\xa1ticas Puras y Aplicadas'), (b'DM', b'Departamento de Mec\xc3\xa1nica'), (b'DPS', b'Departamento de Procesos y Sistemas'), (b'DQ', b'Departamento de Qu\xc3\xadmica'), (b'DTFT', b'Departamento de Termodin\xc3\xa1mica y Fen\xc3\xb3menos de Transferencia')], max_length=4),
        ),
    ]
